#############################################################################
#############################################################################
###                           1) CHECK HEALTH MS                          ###
#############################################################################
#############################################################################

#############################################################
# 1) Health check sui microservizi del GATEWAY
# STATUS: ALL 200
# RISULTATO ATTESO: tutti i servizi up & running
#############################################################################
GET {{$dotenv GTW_CONFIG}}/status
#############################################################################
GET {{$dotenv GTW_DISPATCHER}}/status
#############################################################################
GET {{$dotenv GTW_VALIDATOR}}/status
#############################################################################
GET {{$dotenv GTW_STATUS_CHECK}}/status
#############################################################################
GET {{$dotenv GTW_STATUS_MANAGER}}/status
#############################################################################
GET {{$dotenv GTW_INDEXER}}/status
#############################################################################
GET {{$dotenv GTW_INI_CLIENT}}/status
#############################################################################
GET {{$dotenv GTW_FHIR_MAPPING_ENGINE}}/status
#############################################################################
GET {{$dotenv GTW_PUBLISHER}}/status
#############################################################################
GET {{$dotenv GTW_EDS_CLIENT}}/status
#############################################################################
GET {{$dotenv INI_CLIENT}}/status
#############################################################################


#############################################################
# 1) Health check sui microservizi della UAR
# STATUS: ALL 200
# RISULTATO ATTESO: tutti i servizi up & running
#############################################################################
GET {{$dotenv ANA}}/status
#############################################################################
GET {{$dotenv BROKER}}/status
#############################################################################
GET {{$dotenv UAR_DISPATCHER}}/status
#############################################################################
GET {{$dotenv UAR_INGESTION}}/status
#############################################################################
GET {{$dotenv UAR_DATAREPO_PROCESSOR}}/status
#############################################################################
GET {{$dotenv UAR_DATAREPO_DATA_QUALITY}}/status
#############################################################################
GET {{$dotenv UAR_SRV_QUERY}}/status
#############################################################################
GET {{$dotenv UAR_FHIR_SERVER}}/actuator/health
#############################################################################
GET {{$dotenv BFF}}/status
#############################################################################